FROM node:8-alpine

RUN apk add git
RUN git clone https://github.com/ornicar/chessground.git

WORKDIR /chessground
RUN npm install gulp-cli
RUN ./node_modules/.bin/gulp dev

CMD cat dist/chessground.js
